# Stage 1: Build
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
# Instalamos todas as dependências (incluindo devDependencies para o build)
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Dependencies pruning
FROM node:22-alpine AS dependencies
WORKDIR /app
COPY package*.json ./
# Instalamos apenas as dependências de produção para a imagem final
RUN npm ci --only=production

# Stage 3: Final Image
FROM node:22-alpine
WORKDIR /app
COPY --from=dependencies /app/package*.json ./
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=dependencies /app/package-lock.json ./package-lock.json
COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["node", "dist/src/main.js"]
